### PR TITLE
Fix man page example for timing multiply

### PR DESCRIPTION
**Pull request by pspacek**
Value 0.5 shortens the interval to one half, i.e. doubles the speed.

### CODE REVIEW

**Comment by jelu** [comment]
#build

**Comment by Brian-Rojas** [comment]
Latest libpcap: 1.8.1
I have to stay on 10.3 for FreeBSD

**Comment by jelu** [comment]
@Brian-Rojas I just noticed that you use `client_pool target "0.0.0.0" "53"`, IP address `0.0.0.0` is regarded as any IP address and the behavior may be very different between systems. Try using a real IP address.

**Comment by Brian-Rojas** [comment]
Great observation, however I use the real IP I just put 0.0.0.0 to hide real one.
  

  
  

  
  
>

**Comment by jelu** [comment]
@Brian-Rojas another thing is that `2017-09-06 19:23:14 client_pool.c:0500 network error: client send failed` is present when you used `timing ignore`, may be some system constraint. Have you added more `-v` to see if you can see anything else?

**Pull request merged**
